# general
spring:
  application:
    name: accommodation
  profiles:
    active: "dev"
server:
  port: 8070
  error:
    include-exception: true
    include-stacktrace: always
# logging
# OFF << FATAL << ERROR << WARN << INFO << DEBUG << TRACE << ALL
logging:
  level.com.example.demo: "DEBUG"
validation:
  nameBlackList:
    - "Free"
    - "Offer"
    - "Book"
    - "Website"
  nameSymbolsMin: 10
  ratingMin: 0
  ratingMax: 5
  categoryWhiteList:
    - "hotel"
    - "alternative"
    - "hostel"
    - "lodge"
    - "resort"
    - "guest-house"
  zipCodeLength: 5
  reputationMin: 0
  reputationMax: 1000
  reputationRedThreshold: 500
  reputationYellowThreshold: 799
  reputationRedBadge: "red"
  reputationYellowBadge": "yellow"
  reputationGreenBadge: "green"
  errorMsgNameContainsRestrictedWords: Hotel name "%s" contains restricted words [%s]
  errorMsgNameIsShort: Hotel name "%s" length must be longer than %d
  errorInvalidRating: Hotel rating "%d" must be [%d, %d]
  errorInvalidCategory: Hotel category %s must be one of the words [%s]
  errorImageUrl: Hotel image URL "%s" is invalid, error "%s"
  errorLocationZipCode: Location zip code "%d" must have a length of %d
  errorReputation: Hotel reputation "%d" must be [%d, %d]