# general
spring:
  application:
    name: accommodation
  datasource:
    #url: "jdbc:h2:mem:testdb"
    url: "jdbc:h2:file:P:/data/sample;DB_CLOSE_ON_EXIT=FALSE;"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: ""
    jpa:
      show-sql: true
      database-platform: "org.hibernate.dialect.H2Dialect"
      defer-datasource-initialization: true
      generate-ddl: true
      hibernate:
        ddl-auto: update
    # Enabling H2 Console
  h2:
    console:
      enabled: true
      path: "/h2"
server:
  port: 8070
# logging
# OFF << FATAL << ERROR << WARN << INFO << DEBUG << TRACE << ALL
logging:
  level.com.example.demo: "DEBUG"
validation:
  nameBlackList:
    - "Free"
    - "Offer"
    - "Book"
    - "Website"
  nameSymbolsMin: 10
  ratingMin: 0
  ratingMax: 5
  categoryWhiteList:
    - "hotel"
    - "alternative"
    - "hostel"
    - "lodge"
    - "resort"
    - "guest-house"
  zipCodeLength: 5
  reputationMin: 0
  reputationMax: 1000
  reputationRedThreshold: 500
  reputationYellowThreshold: 799