DROP TABLE IF EXISTS locations;
CREATE TABLE  locations (
  location_id INT AUTO_INCREMENT PRIMARY KEY,
  city VARCHAR(255) DEFAULT NULL,
  state VARCHAR(255) DEFAULT NULL,
  country VARCHAR(255) DEFAULT NULL,
  zip_code INT DEFAULT 0,
  address VARCHAR(255) DEFAULT NULL
);
DROP TABLE IF EXISTS hotels;
CREATE TABLE hotels (
  hotel_id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) DEFAULT NULL,
  rating INT DEFAULT 0,
  category VARCHAR(20) DEFAULT NULL,
  location_id INT,
  image VARCHAR(255) DEFAULT NULL,
  reputation INT DEFAULT 0,
  reputation_badge VARCHAR(10) DEFAULT NULL,
  price INT DEFAULT 0,
  availability INT DEFAULT 0,
  FOREIGN KEY (location_id) REFERENCES locations(location_id) ON DELETE SET NULL
);